/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import proyecto.MenuPrincipal;
import proyecto.dbConexion;

/**
 *
 * @author PC
 */
public class MenuConsultas extends javax.swing.JFrame {

    dbConexion db = new dbConexion();
    Connection conect;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;

    public MenuConsultas() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        agTempCategoria = new javax.swing.JPanel();
        imgTemp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        consHotelPais = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVolverMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione un tipo de consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 18))); // NOI18N

        agTempCategoria.setBackground(new java.awt.Color(255, 255, 255));
        agTempCategoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/img/temporadaLogo.png"))); // NOI18N
        imgTemp.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 2, new java.awt.Color(0, 204, 255)));
        agTempCategoria.add(imgTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 70, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/img/hotelCategLogo.png"))); // NOI18N
        jLabel2.setText("CONSULTA DE TEMPORADAS Y CATEGORIAS");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 0, new java.awt.Color(0, 204, 255)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        agTempCategoria.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, 68));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consHotelPais.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        consHotelPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/img/paises.png"))); // NOI18N
        consHotelPais.setText("CONSULTA DE HOTELES POR PAIS");
        consHotelPais.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 0, new java.awt.Color(0, 204, 255)));
        consHotelPais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consHotelPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consHotelPaisMouseClicked(evt);
            }
        });
        jPanel2.add(consHotelPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 310, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/img/hoteliMG.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 2, new java.awt.Color(0, 204, 255)));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 60, -1));

        btnVolverMenu.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnVolverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/img/volverLogo.png"))); // NOI18N
        btnVolverMenu.setText("VOLVER AL MENU");
        btnVolverMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 204, 255)));
        btnVolverMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agTempCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(agTempCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnVolverMenu)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        HotelCategoria hotelCat = new HotelCategoria();
        this.dispose();
        hotelCat.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void consHotelPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consHotelPaisMouseClicked
        // TODO add your handling code here:
        HotelesPaises hotelP = new HotelesPaises();
        this.dispose();
        hotelP.setVisible(true);
    }//GEN-LAST:event_consHotelPaisMouseClicked

    private void btnVolverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseClicked
        // TODO add your handling code here:
        MenuPrincipal menP = new MenuPrincipal();
        this.dispose();
        menP.setVisible(true);
    }//GEN-LAST:event_btnVolverMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agTempCategoria;
    private javax.swing.JLabel btnVolverMenu;
    private javax.swing.JLabel consHotelPais;
    private javax.swing.JLabel imgTemp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
